sudo: required
dist: trusty
language: cpp

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-sdk-team/ppa'
    packages:
      - gdb
      - qt5-qmake
      - qtbase5-dev
      - qtdeclarative5-dev
      - libqt5webkit5-dev
      - libsqlite3-dev

matrix:
  include:
    - os: linux

before_install:
  - sudo apt-get install -qq pkg-config fuse
  - sudo modprobe fuse

before_script:
  - cd src

script:
  - qmake -qt=qt5 routegen.pro CONFIG+=release
  - make

after_success:
  - export VERSION=$(head -n 1 ../CHANGELOG.md | awk '{print $1}')
  - make INSTALL_ROOT=build/appdir -j$(nproc) install; find build/appdir/
  - cd build
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - mkdir -p packages && cd packages
  - unset QTDIR; unset QT_PLUGIN_PATH; unset LD_LIBRARY_PATH
  - ../linuxdeployqt-continuous-x86_64.AppImage ../appdir/usr/local/share/applications/routegen.desktop -qmake="qmake -qt=qt5" -appimage -extra-plugins=platforms/libqxcb.so

deploy:
  provider: releases
  api_key:
    secure: golz8jGgEVz9NKsTcah+1X63yAaM1LmBKnQKbLzGQkO8LlmYjChIw8q1Znhy2+y9IXy9ShRazR9a8eiAt6JgOY1xjG8VlatqlerCmIJyXApkzKkMBzsGadkMzBwkFe7fEnHZtYMvJ5oEegCDSa/8iqghZdASrlznZswh4OBAMTKNQJbrA+rg0NII14YxsAWFItX7f1c7r7cG0gcQLiEAXkN2lI0BLZO3zGxwkbilaEzqOvn6OqJ6TXpwbh9uV4jFyw/QAvjsaaWjPviKMsRoWlVpNY6WovpueZqInS8MqUmWffyhdhG8bW7OtMn5UGv3fypSjkdJScTowgdQ4/j4A2xlvlNDBTgxLV5fGOfJigmHuiMTWRVaUxowJKgLDHFWDaERmlt2sGLRHA10uh4fmo0asRtiKtlyZPn+MHAs+7Q4ZWoxIeSZvH8aHmVvAYrDLnR2DVxunkd+yAfn3n2N1vZbIvM5cgtS2HA27FTyVtDkqI7x4/jkTGEjaMybDTAhgxWc29/V6ykc4/QwIT/46NhPzSdNjN7T/ZOFCwhGHjwveWLEt+AhDeESM/huY94ZW8QZy9xEJ39c2iCtKcRIL+Hjj3+awx2L2RS+cMnG8p4PJwIXKp4KjF5V4gQ2/EFucCxo32DOCHwiFK10BWy1zC7GngNAhZ20yYJo5+kF+58=
  file_glob: true
  file: ./*
  skip_cleanup: true
  on:
    repo: WanderlandTravelers/routegen
    all_branches: true
    tags: false