dist: trusty
language: cpp

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-sdk-team/ppa'
    packages:
      - gdb
      - qt5-qmake
      - qtbase5-dev
      - qtdeclarative5-dev
      - libqt5webkit5-dev
      - libsqlite3-dev

matrix:
  include:
    - os: linux

before_script:
  - cd src

script:
  - qmake -qt=qt5 routegen.pro
  - make

